### ISSUE TITLE
Dockerfileの.lockと.txtが逆

### ISSUE THREAD

**Issue by momotaro98** [rhoboro/webapp_skeleton#1]
こんにちは。

こちらのプロジェクト、参考にさせていただいていますが、以下の箇所にて`requirements.lock`と`requirements.txt`が逆ではないかと思っています。

```
RUN if [ -z "$UPDATE_LOCK" ]; then pip install --no-cache-dir -r requirements.lock; fi
RUN pip install --no-cache-dir -r requirements.txt
```

https://github.com/rhoboro/webapp_skeleton/blob/4e0907957e/Dockerfile#L8-L9

UPDATE_LOCKをするときにrequirements.txtを参照し更新。
dev, productionで動かすときは、requirements.lockでインストールするはずなので。

**Comment by rhoboro** [comment]
@momotaro98 
ありがとうございます！
ここですが、とても紛らわしくてすいません :bow:
次のような動きになっていたと思います

* 通常時
    * `$UPDATE_LOCK`が空なのでif文が真になる
    * `pip install --no-cache-dir -r requirements.lock`が実行される 
    * 次の行はすべて`Requirement already satisfied`になることを期待しています。
* アップデート時
    * [$UPTATE_LOCKが1](https://github.com/rhoboro/webapp_skeleton/blob/4e0907957e3326d00ee4d57da7dcb7df743700af/Makefile#L6)でif文が偽となる
    * `pip install --no-cache-dir -r requirements.lock`はスキップされる
    * 次の行で最新版が入る

**Comment by momotaro98** [comment]
@rhoboro 
回答ありがとうございます！
すみません、私の方で勘違いしておりまして、手元で実行したところ確かにそのような動作となりました。
お手数おかけしました。
